In [1]:
import numpy as np
import random as r
#Exercici 1 de la tarea 2 del Sprint 3
a = np.array([r.randint(0,25) for i in range(8)], dtype=np.int16)

In [2]:
a.ndim

1

In [3]:
print(a)

[11 10 14  1 11 10  4 24]


In [4]:
#calculo el valor mitjà
np.mean(a)

10.625

In [5]:
#resto la mitjana resultant
a - np.median(a)

array([ 0.5, -0.5,  3.5, -9.5,  0.5, -0.5, -6.5, 13.5])

In [6]:
#Creo matriu 5x5
b = np.array([[r.randint(0,25) for i in range(5)] for x in range(5)], dtype=np.int16)
print(b)

[[10 21  8 12 19]
 [ 4  2 24  2 20]
 [ 1 21 21  4  0]
 [17 21 25  4  1]
 [ 1 10  0  8 19]]


In [7]:
#El valor màxim de la matriu
np.max(b)

25

In [8]:
#El valor màxim de cada eix de la matriu
b.max(axis=1)

array([21, 24, 21, 25, 19], dtype=int16)

In [9]:
#Nivell 2
#Mostrar que el broadcasting només és possible si coincideixen les
#dimensions o una matriu té mida = 1

c = np.array([r.randint(0,10) for i in range(8)])

In [10]:
#Arrays amb mides 1 i 2 per fer proves
test1 = np.array([r.randint(0,10) for i in range(1)])
test2 = np.array([r.randint(0,10) for i in range(2)])

In [11]:
#És possible operar amb la array "c" i "test1" que té mida 1, però no amb "test2"
c + test1

array([14,  4, 14, 10,  9,  7,  5, 11])

In [12]:
c * test1

array([40,  0, 40, 24, 20, 12,  4, 28])

In [13]:
c + test2

ValueError: operands could not be broadcast together with shapes (8,) (2,) 

In [14]:
c * test2

ValueError: operands could not be broadcast together with shapes (8,) (2,) 

In [15]:
#Exercici 5, extreure valors d'una fila i una columna, per això utilitzaré la array b inicialitzada en un exercici anterior

l_fila = b[1] #Agafo la segona fila
l_fila

array([ 4,  2, 24,  2, 20], dtype=int16)

In [16]:
l_colum = b[:,2] #Agafo la tercera columna
l_colum

array([ 8, 24, 21, 25,  0], dtype=int16)

In [17]:
#Sumo els seus valors
l_fila + l_colum

array([12, 26, 45, 27, 20], dtype=int16)

In [29]:
#a

In [19]:
#Exercici 7, importo llibreries i carrego la foto
import matplotlib.image as mpimg
img = mpimg.imread("20170904_165255.jpg")

In [20]:
#Visualitzo les dades
print(img)

[[[ 79  79  79]
  [ 78  78  78]
  [ 75  75  75]
  ...
  [ 35  36  30]
  [ 37  38  32]
  [ 38  39  33]]

 [[ 77  77  77]
  [ 77  77  77]
  [ 74  74  74]
  ...
  [ 36  37  31]
  [ 38  39  33]
  [ 36  37  31]]

 [[ 76  76  76]
  [ 76  76  76]
  [ 74  74  74]
  ...
  [ 37  38  32]
  [ 38  39  33]
  [ 36  37  31]]

 ...

 [[223 227 228]
  [224 228 229]
  [222 226 227]
  ...
  [ 19  21  20]
  [ 21  23  22]
  [ 22  24  23]]

 [[223 227 228]
  [223 227 228]
  [222 226 227]
  ...
  [ 18  20  19]
  [ 20  22  21]
  [ 21  23  22]]

 [[223 227 228]
  [223 227 228]
  [221 225 226]
  ...
  [ 18  20  19]
  [ 19  21  20]
  [ 21  23  22]]]


In [21]:
#Les manipulo editant tots els valors
img += 30
print(img)

[[[109 109 109]
  [108 108 108]
  [105 105 105]
  ...
  [ 65  66  60]
  [ 67  68  62]
  [ 68  69  63]]

 [[107 107 107]
  [107 107 107]
  [104 104 104]
  ...
  [ 66  67  61]
  [ 68  69  63]
  [ 66  67  61]]

 [[106 106 106]
  [106 106 106]
  [104 104 104]
  ...
  [ 67  68  62]
  [ 68  69  63]
  [ 66  67  61]]

 ...

 [[253   1   2]
  [254   2   3]
  [252   0   1]
  ...
  [ 49  51  50]
  [ 51  53  52]
  [ 52  54  53]]

 [[253   1   2]
  [253   1   2]
  [252   0   1]
  ...
  [ 48  50  49]
  [ 50  52  51]
  [ 51  53  52]]

 [[253   1   2]
  [253   1   2]
  [251 255   0]
  ...
  [ 48  50  49]
  [ 49  51  50]
  [ 51  53  52]]]


In [22]:
#Deso la imatge
mpimg.imsave("prova_ex7.jpg",img)

In [23]:
#Carrego un altre cop la imatge original
img2 = mpimg.imread("20170904_165255.jpg")

In [24]:
#Elimino la tercera columna de valors, on es guarden els valors del blau
img_sense_blau = np.delete(img2,2,2)

In [25]:
#Intento desar la imatge pero no em deixarà ja que no accepta arrays amb 2 valors
mpimg.imsave("prva_senseblau_ex8.jpg",img_sense_blau)

ValueError: Third dimension must be 3 or 4

In [26]:
#En canvi, si canviem el valor per 0, si que ens deixa i elimina tot color blau de la imatge
img2[:,:,2] = 0

In [27]:
mpimg.imsave("prva_senseblau_ex8_2.jpg",img2)